# Generated by Django 4.2.7 on 2026-08-24 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 7, 12, 22, 44, 469102)),
        ),
    ]
