# Generated by Django 4.2.7 on 2026-08-25 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_post_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 9, 8, 4, 20, 14, 681145)
            ),
        ),
    ]
