# Generated by Django 4.2.7 on 2026-08-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('national_id_encrypted', models.CharField(max_length=255)),
                ('group_number', models.IntegerField()),
                ('phone_encrypted', models.CharField(max_length=255)),
                ('father_phone_encrypted', models.CharField(blank=True, max_length=255)),
                ('mother_phone_encrypted', models.CharField(blank=True, max_length=255)),
                ('attendance_percentage', models.FloatField(default=100.0)),
                ('warnings_count', models.IntegerField(default=0)),
                ('accepted_rules', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('national_id_encrypted', models.CharField(default='', max_length=255)),
                ('phone_encrypted', models.CharField(default='', max_length=255)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
    ]
